### ISSUE TITLE
Function & Tabulation errors

### ISSUE THREAD

**Issue by SkyCraft78** [Romitou/Skript-Nexus#4] opened 2020-10-19 13:06 UTC
Hey ! First, thanks for making this converter, he's very helpfull !
I found some bugs while converting my TuSke code.
The first one is about function.
TuSke's code is : 
```create gui slot 0 of {_p} with {_i} to run function openCraftGUI({_p},getCraftType({_v}),getItem({_v}),getCraft({_v}))```
This will be convert with : 
```make gui slot 0 with {_i}:```
```    function openCraftGUI({_p},getCraftType({_v}),getItem({_v}),getCraft({_v}))```
For the second, it's about Tabulation.
I don't really know why, but he change some Tabulation with 4 spaces (I've been check the "Use tabulation" mark!)
Sorry, I don't have realy example of it. I can just show you one of my code if you need it.
Thanks you and good day ;)

**Comment by Romitou** [comment] 2020-10-19 13:21
Hello, thank you for opening an issue to inform me of these problems!
I will investigate and correct this as soon as possible.
Have a nice day!

**Comment by Romitou** [comment] 2020-10-27 12:07
Hello, support for several functions has been added!
However, for the indentation issue, I was not able to reproduce this. Can you send me your code? Please make sure you have tried with a complete code as the converter relies on various elements.
Thank you, have a nice day.

**Comment by Romitou** [comment] 2020-11-13 20:44
No answer, so the problem seems to be solved. I'm closing.

**Closed by Romitou** 2020-11-13 20:44 UTC
Labels: bug, waiting for response
